/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import javax.imageio.IIOException;
import java.io.IOException;
import java.lang.module.FindException;
import java.util.*;

public class App {


    public static void main(String[] args) {

        System.out.println("Train Booking System is Running......!!!!");
        Scanner scanner = new Scanner(System.in);
        int option =0;
        UserBookingService userBookingService;

        try{
            userBookingService = new UserBookingService();
        }catch (IOException e){
            System.out.println("Something went wrong : "+e.getMessage());
            return;
        }
        while(option != 7){
            System.out.println("choose options");
            System.out.println("1. Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel My Booking");
            System.out.println("7. Exit the App");

            option = scanner.nextInt();
            Train trainSelectedForBooking = new Train();

            switch (option){
                case 1:
                    System.out.println("Enter the username to singUp");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter a password to signUp");
                    String passwordToSignUp = scanner.next();
                    User userToSignUp = new User(nameToSignUp,
                            passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter username to login");
                    String usernameToLogin = scanner.next();
                    System.out.println("Enter password to login");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User(usernameToLogin,
                            passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin),new ArrayList<>(),UUID.randomUUID().toString());

                    try{
                        userBookingService = new UserBookingService(userToLogin);
                        if(userBookingService.loginUser()){
                            System.out.println("Login successful!");
                        }else {
                            System.out.println("Invalid username or password");
                        }
                    } catch (IOException e) {
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your booking");
                    if(!userBookingService.isUserLogin()){
                        System.out.println("You need to login first!");
                        break;
                    }
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station ");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String destination = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source,destination);
                    int index =1;
                    for(Train train : trains){
                        System.out.println(index +" Train id : "+train.getTrainId());
                        for (Map.Entry<String,String> entry : train.getStationTimes().entrySet()){
                            System.out.println("Station "+entry.getKey() +" time : "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    int choice = scanner.nextInt();
                    if(choice <= 0 || choice > trains.size()){
                        System.out.println("Invalid selection");
                        break;
                    }
                    trainSelectedForBooking = trains.get(choice - 1);
                    break;
                case 5:
                    if(trainSelectedForBooking == null){
                        System.out.println("Please search and select a train first (Option 4)");
                        break;
                    }
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    if(seats == null){
                        System.out.println("Seats data not available for this train.");
                        break;
                    }
                    for(List<Integer> row : seats){
                        for(Integer val : row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seats by typing the row and column");
                    System.out.println("Enter the row");
                    int row = scanner.nextInt();
                    System.out.println("Enter the column");
                    int col = scanner.nextInt();
                    System.out.println("Booking your seats...");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking,row,col);

                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Enjoy! Your ticket is booked");
                    }else{
                        System.out.println("Sorry ! your ticket can't be booked");
                    }
                    break;
                case 6:
                    System.out.println("Enter your train Id.:- ");
                    String trainId = scanner.next();
                    if(trainId == null){
                        System.out.println("Please enter a valid train Id");
                    }
                    Boolean cancelled = userBookingService.cancelBooking(trainId);

                    if(cancelled.equals(Boolean.TRUE)){
                        System.out.println("Booking has been cancelled");
                    }else {
                        System.out.println("Cancellation failed. Please check the ticket ID.");
                    }
                    break;
                case 7:
                    System.out.println("Thank you for using our service.!Good Bye USER");
                    scanner.close();
                    System.exit(0);
                    break;
                default:
                    break;




            }
        }
    }
}
