/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import javax.imageio.IIOException;
import java.io.IOException;
import java.lang.module.FindException;
import java.util.*;

public class App {


    public static void main(String[] args) {

        System.out.println("Train Booking System is Running......!!!!");
        Scanner scanner = new Scanner(System.in);
        int option =0;
        UserBookingService userBookingService;

        try{
            userBookingService = new UserBookingService();
        }catch (IOException e){
            System.out.println("Something went wrong"+e);
            return;
        }
        while(option != 7){
            System.out.println("choose options");
            System.out.println("1. Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel My Booking");
            System.out.println("7. Exit the App");

            option = scanner.nextInt();

            switch (option){
                case 1:
                    System.out.println("Enter the username to singUp");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter a password to signUp");
                    String passwordToSignUp = scanner.next();
                    User userToSignUp = new User(nameToSignUp,
                            passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter username to login");
                    String usernameToLogin = scanner.next();
                    System.out.println("Enter password to login");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User(usernameToLogin,
                            passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin),new ArrayList<>(),UUID.randomUUID().toString());

                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    } catch (IOException e) {
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your booking");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station ");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String destination = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source,destination);
                    for(Train train : trains){
                        System.out.println(FindException +" Train id : "+train.getTrainId());
                        for (Map.Entry<String,String> entry : train.getStationTimes().entrySet()){
                            System.out.println("Station "+entry.getKey() +" time : "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    trainSelectedBooking= trains.get(scanner.nextInt());
                    break;
                case 5:



            }
        }
    }
}
